### ISSUE TITLE
OS in python, or C?

### ISSUE THREAD

**Issue by mojidev-py** [XenonPy/clios#1]
So, I was wandering around your profile, since you very kindly accepted to contribute to my project, and I stumbled upon this! Very ambitious project. I was wondering though: How would you setup the environment for Python? Python is a very high-level language (as you probably know), and it's pretty slow. If you use Cython, it would be cool, but the environment for python... Linux kernel maybe? (Use an LTS version).
I just wanted to open this issue to bring up some questions I have 😄

**Comment by XenonPy** [comment]
yeah... im trying to make a kernel that just runs a python cli, and then this would run on that

**Comment by mojidev-py** [comment]
oh.... so It's in C/Rust? Cool! (I'm dying inside because I want to learn rust so bad 😢 )
